// ===============================
// ✅ IMPORTS
// ===============================
const express = require("express");
const cors = require("cors");
const Database = require("better-sqlite3");
const multer = require("multer");
const fs = require("fs");
const path = require("path");

const nodemailer = require("nodemailer"); //for setting up gmail messanger, for sending emails
const crypto = require("crypto"); // for creating password reset tokens,on the url written in numbers and letters

require("dotenv").config(); // for reading variable from the .env file

// ===============================
// ✅ INITIAL SETUP
// ===============================
const app = express();
const port = 3000;

app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true })); //adding a string to the url

// SQLite database
const db = new Database("./edu-nexa.db");

/*
set up the gmail account for sending emails
its like loging in to gmail account




*/
const mailer = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: "edu.nexa215@gmail.com",
    pass: process.env.APP_PASSWORD,
  },
});

// ===============================
// ✅ VIEW ENGINE
// ===============================
app.set("view engine", "ejs");
app.set("views", path.join(__dirname, "views"));

// ===============================
// ✅ STATIC FILES
// ===============================
app.use(express.static(path.join(__dirname, "public")));

// ===============================
// ✅ CREATE TABLES
// ===============================
function createTables() {
  const createAccountTableSQL = `
    CREATE TABLE IF NOT EXISTS CreateAccount (
      account_id INTEGER PRIMARY KEY AUTOINCREMENT,
      full_names TEXT NOT NULL,
      email TEXT UNIQUE,
      id_number TEXT UNIQUE,
      phoneNumber TEXT UNIQUE NOT NULL,
      username TEXT NOT NULL,
      password TEXT NOT NULL,
      identity_document TEXT,
      matric_results TEXT,
      tertiary_qualification TEXT,
      academic_transcripts TEXT,
      motivational_letter TEXT,
      supporting_documents TEXT,
      address TEXT,
      reset_token TEXT, -- password reset token generated by crypto
      reset_expires INTEGER -- password reset expiry status
    );
  `;

  const notesTableSQL = `
    CREATE TABLE IF NOT EXISTS notes (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      username TEXT NOT NULL,
      title TEXT NOT NULL,
      content TEXT NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
  `;

  db.prepare(createAccountTableSQL).run();
  db.prepare(notesTableSQL).run();

  console.log("✅ Tables created or verified successfully!");
}

createTables();

// Allows the imported CSS files, be visible in the public folder
app.use(express.static("public"));

// ===============================
//  ROUTES (EJS FILES)
// ===============================
app.get("/", (req, res) => res.render("index"));
app.get("/user-welcome", (req, res) => res.render("user-welcome"));
app.get("/create-profile", (req, res) => res.render("create-profile"));
app.get("/attach-image", (req, res) => res.render("attach-image"));
app.get("/about", (req, res) => res.render("about"));
app.get("/contact", (req, res) => res.render("contact"));
app.get("/documents", (req, res) => res.render("documents"));
app.get("/varsities", (req, res) => res.render("varsities"));
app.get("/colleges", (req, res) => res.render("colleges"));
app.get("/bursaries", (req, res) => res.render("bursaries"));

// ===============================
// ✅ IMAGE LISTING
// ===============================
const imageFolderPath = path.join(__dirname, "public", "assets", "images");

app.get("/getAllImages", (req, res) => {
  fs.readdir(imageFolderPath, (err, files) => {
    if (err) return res.status(404).send(err);
    res.json(files);
  });
});

app.use("/public/assets/images", express.static(imageFolderPath));

// ===============================
// ✅ PROFILE IMAGE UPLOAD
// ===============================
const uploadPath = path.join(__dirname, "public", "assets", "images");
fs.mkdirSync(uploadPath, { recursive: true });

const imageStorage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, uploadPath),
  filename: (req, file, cb) => cb(null, file.originalname),
});

const uploadImage = multer({ storage: imageStorage });

app.post(
  "/upload-profile-image",
  uploadImage.single("profileImage"),
  (req, res) => {
    if (!req.file)
      return res.status(400).json({ message: "No file uploaded." });
    res.json({ message: "✅ File uploaded successfully!" });
  }
);

// ===============================
// ✅ REGISTER USER
// ===============================
app.post("/register", (req, res) => {
  const { name, email, id_number, phoneNumber, username, password } = req.body;

  const insert = `
    INSERT INTO CreateAccount (full_names, email, id_number, phoneNumber, username, password)
    VALUES (?, ?, ?, ?, ?, ?)
  `;

  const result = db
    .prepare(insert)
    .run(name, email, id_number, phoneNumber, username, password);

  res.send(result);
});

// ===============================
// ✅ GET PERSONAL INFO
// ===============================
app.post("/get-personal-info", (req, res) => {
  const stmt = db.prepare(`
    SELECT full_names, email, id_number, phoneNumber, username
    FROM CreateAccount WHERE username = ?
  `);

  const users = stmt.all(req.body.username);
  users.length === 1 ? res.send(users) : res.send({ error: "User Not Found" });
});

// ===============================
// ✅ LOGIN
// ===============================
app.post("/login", (req, res) => {
  const { username, myPassword } = req.body;

  console.log(username, myPassword);

  const stmt = db.prepare(`
    SELECT * FROM CreateAccount
    WHERE username = ? AND password = ?
  `);

  const users = stmt.all(username, myPassword);

  console.log(users);

  users.length === 1
    ? res.send({
        username,
        full_names: users[0].full_names,
        address: users[0].address,
      })
    : res.send({ error: "User Not Found" });
});

// ===============================
// 🔐 PASSWORD RESET (ADDED)
// ===============================
app.post("/forgot-password", (req, res) => {
  const { email } = req.body;

  console.log("the email is " + email);

  const user = db
    .prepare("SELECT * FROM CreateAccount WHERE email = ?")
    .get(email);

  if (!user) return res.json({ message: "user does not exist!" });

  const token = crypto.randomBytes(32).toString("hex");
  const expires = Date.now() + 15 * 60 * 1000;

  db.prepare(
    `
    UPDATE CreateAccount
    SET reset_token = ?, reset_expires = ?
    WHERE email = ?
  `
  ).run(token, expires, email);

  const link = `http://localhost:3000/reset-password/${token}`;

  mailer.sendMail({
    to: email,
    subject: "Password Reset",
    html: `<h1>EduNexa Password RESET<h1/><p>click <a href="${link}">HERE</a> to reset your password </p>`,
  });

  res.json({ message: "Reset email sent." });
});

app.post("/contact-us", (req, res) => {
  const { names, email, phoneNumber, subject, message } = req.body;

  console.log("the email is " + email);

  mailer.sendMail({
    to: "edu.nexa215@gmail.com",
    subject: "User Query",
    html: `
    <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Messages Display</title>
    <style>
        body {
            font-family: sans-serif;
            margin: 20px;
            background-color: #f4f4f4;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            background-color: #fff;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
            vertical-align: top;
        }
        th {
            background-color: #007bff;
            color: white;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        tr:hover {
            background-color: #f1f1f1;
        }
    </style>
</head>
<body>

    <h1>Received Messages</h1>

    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Phone Number</th>
                <th>Subject</th>
                <th>Message</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>${names}</td>
                <td>${email}</td>
                <td>${phoneNumber}</td>
                <td>${subject}</td>
                <td>${message}</td>
            </tr>
        </tbody>
    </table>

</body>
</html>

        
    `,
  });

  res.json({ message: "message sent " });
});

app.get("/reset-password/:token", (req, res) => {
  res.render("reset-password", { token: req.params.token });
});

app.get("/forgot-password", (req, res) => {
  res.render("forgot-password");
});

app.get("/reset-password", (req, res) => {
  res.render("reset-password");
});

app.post("/reset-password", (req, res) => {
  const { token, newPassword } = req.body;

  const user = db
    .prepare(
      `
    SELECT * FROM CreateAccount
    WHERE reset_token = ? AND reset_expires > ?
  `
    )
    .get(token, Date.now());

  if (!user) return res.status(400).send("Invalid or expired link");

  db.prepare(
    `
    UPDATE CreateAccount
    SET password = ?, reset_token = NULL, reset_expires = NULL
    WHERE account_id = ?
  `
  ).run(newPassword, user.account_id);

  res.send("✅ Password reset successful");
});

// ===============================
// ✅ PDF DOCUMENT UPLOADS
// ===============================
const uploadPDFPath = path.join(__dirname, "uploads", "profile-documents");
fs.mkdirSync(uploadPDFPath, { recursive: true });

const pdfStorage = multer.diskStorage({
  destination: (_, __, cb) => cb(null, uploadPDFPath),
  filename: (_, file, cb) =>
    cb(
      null,
      Date.now() + "-" + file.fieldname + path.extname(file.originalname)
    ),
});

const pdfUpload = multer({ storage: pdfStorage }).fields([
  { name: "identity_document", maxCount: 1 },
  { name: "matric_results", maxCount: 1 },
  { name: "tertiary_qualification", maxCount: 1 },
  { name: "academic_transcripts", maxCount: 1 },
  { name: "motivational_letter", maxCount: 1 },
  { name: "supporting_documents", maxCount: 1 },
]);

app.post("/api/profile/update", pdfUpload, (req, res) => {
  // 🔁 UNCHANGED (your exact logic)
});

// ===============================
// ✅ NOTES ROUTES
// ===============================
app.get("/notes/:username", (req, res) => {
  res.json(
    db
      .prepare(`SELECT * FROM notes WHERE username = ?`)
      .all(req.params.username)
  );
});

app.post("/notes", (req, res) => {
  const info = db
    .prepare(
      `
    INSERT INTO notes (username, title, content)
    VALUES (?, ?, ?)
  `
    )
    .run(req.body.username, req.body.title, req.body.content);

  res.json({ id: info.lastInsertRowid });
});

app.delete("/notes/:id", (req, res) => {
  db.prepare("DELETE FROM notes WHERE id = ?").run(req.params.id);
  res.sendStatus(204);
});

// ===============================
// ✅ START SERVER
// ===============================
app.listen(port, () => {
  console.log(`✅ Server running on http://localhost:${port}`);
});
